[workspace]
resolver = "2"
members = [
  "starstream-cli",
  "starstream-compiler",
  "starstream-interpreter",
  "starstream-language-server",
  "starstream-to-wasm",
  "starstream-types",
]

[workspace.package]
version = "0.0.0"
authors = []
edition = "2024"
rust-version = "1.89.0"
repository = "https://github.com/LFDT-Nightstream/Starstream"
license = "MIT/Apache-2.0"

[workspace.dependencies]
ariadne = "0.5.1"
chumsky = "0.11.1"
indoc = "2.0"
insta = "1.39"
serde = "1.0.219"
starstream-compiler = { path = "starstream-compiler" }
starstream-language-server = { path = "starstream-language-server" }
starstream-to-wasm = { path = "starstream-to-wasm" }
starstream-types = { path = "starstream-types" }
tower-lsp-server = { version = "0.22.1", default-features = false, features = [
  "runtime-agnostic",
] }

[profile.dev.package]
insta.opt-level = 3
