[workspace]
package.version = "0.0.0"
package.license = "MIT/Apache-2.0"
package.authors = []
package.edition = "2024"

members = [
    "starstream-cli",
    "starstream-compiler",
    "starstream-interpreter",
    "starstream-to-wasm",
    "starstream-types",
]
resolver = "2"
