cargo-features = ["per-package-target"]

[package]
name = "starstream_sys"
version = "0.0.0"
edition = "2024"
license.workspace = true

forced-target = "wasm32-unknown-unknown"

[lib]
name = "starstream"
test = false

[dependencies]
