// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type UtxoA = starstream_demo::coord_rs::utxo_a_api::Utxo;
pub type UtxoB = starstream_demo::coord_rs::utxo_b_api::Utxo;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(arg0: i32, arg1: i32) {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let handle0;
    let handle1;
    T::main(
        {
            handle0 =
                unsafe { starstream_demo::coord_rs::utxo_a_api::Utxo::from_handle(arg0 as u32) };
            &handle0
        },
        {
            handle1 =
                unsafe { starstream_demo::coord_rs::utxo_b_api::Utxo::from_handle(arg1 as u32) };
            &handle1
        },
    );
}
pub trait Guest {
    fn main(utxo_a: &UtxoA, utxo_b: &UtxoB) -> ();
}
#[doc(hidden)]
macro_rules! __export_world_demo_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : i32, arg1 : i32,) { unsafe { $($path_to_types)*::
        _export_main_cabi::<$ty > (arg0, arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_demo_cabi;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod starstream_demo {
    pub mod coord_rs {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod utxo_a_api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Utxo {
                handle: _rt::Resource<Utxo>,
            }
            impl Utxo {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Utxo {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-a-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]utxo"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl Utxo {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-a-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]utxo"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { Utxo::from_handle(ret as u32) }
                    }
                }
            }
            impl Utxo {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_data(&self) -> u64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-a-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]utxo.get-data"]
                            fn wit_import0(_: i32) -> i64;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) -> i64 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0((self).handle() as i32) };
                        ret as u64
                    }
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod utxo_b_api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Utxo {
                handle: _rt::Resource<Utxo>,
            }
            impl Utxo {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Utxo {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-b-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]utxo"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl Utxo {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-b-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]utxo"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { Utxo::from_handle(ret as u32) }
                    }
                }
            }
            impl Utxo {
                #[allow(unused_unsafe, clippy::all)]
                pub fn increment(&self) -> () {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "starstream-demo:coord-rs/utxo-b-api"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]utxo.increment"]
                            fn wit_import0(_: i32);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) {
                            unreachable!()
                        }
                        unsafe { wit_import0((self).handle() as i32) };
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_demo_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_demo_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_demo_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:starstream-demo:coord-rs:demo:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 486] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xeb\x02\x01A\x02\x01\
A\x0c\x01B\x07\x04\0\x04utxo\x03\x01\x01i\0\x01@\0\0\x01\x04\0\x11[constructor]u\
txo\x01\x02\x01h\0\x01@\x01\x04self\x03\0w\x04\0\x15[method]utxo.get-data\x01\x04\
\x03\0#starstream-demo:coord-rs/utxo-a-api\x05\0\x02\x03\0\0\x04utxo\x03\0\x06ut\
xo-a\x03\0\x01\x01B\x07\x04\0\x04utxo\x03\x01\x01i\0\x01@\0\0\x01\x04\0\x11[cons\
tructor]utxo\x01\x02\x01h\0\x01@\x01\x04self\x03\x01\0\x04\0\x16[method]utxo.inc\
rement\x01\x04\x03\0#starstream-demo:coord-rs/utxo-b-api\x05\x03\x02\x03\0\x01\x04\
utxo\x03\0\x06utxo-b\x03\0\x04\x01h\x02\x01h\x05\x01@\x02\x06utxo-a\x06\x06utxo-\
b\x07\x01\0\x04\0\x04main\x01\x08\x04\0\x1dstarstream-demo:coord-rs/demo\x04\0\x0b\
\x0a\x01\0\x04demo\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compon\
ent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
