[package]
name = "starstream_compiler"
version = "0.0.0"
edition = "2024"
license.workspace = true

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.10.1", features = ["pratt"] }
ena = "0.14.3"
wasm-encoder = "0.229.0"

[dev-dependencies]
wasmparser = "0.229.0"
