[package]
name = "starstream-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Shared types for Starstream DSL"
repository.workspace = true
license.workspace = true

[dependencies]
chumsky = { workspace = true }
quickcheck = { version = "1.0.3", optional = true }
quickcheck_macros = { version = "1.1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"

[features]
quickcheck = ["dep:quickcheck", "dep:quickcheck_macros"]
