[package]
name = "starstream-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Shared types for Starstream DSL"
repository.workspace = true
license.workspace = true

[dependencies]
chumsky = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
