#!/bin/sh
set -eu
target="$(realpath "$(dirname "$0")")"
check() {
    if test -d "$1"; then
        ln -sTf "$target" "$1/starstream-dev"
        echo "Installed to $1"
    fi
}
check ~/.vscode/extensions
check ~/.vscode-oss/extensions
