[package]
name = "starstream-compiler"
description = "Compiler for the Starstream DSL"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.11", features = ["pratt"] }
pretty = "0.12.5"
starstream-types = { path = "../starstream-types" }

[dev-dependencies]
indoc = "2.0"
insta = "1.39"
