[package]
name = "starstream-compiler"
description = "Compiler for the Starstream DSL"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
starstream-types = { path = "../starstream-types" }
chumsky = { version = "0.11", features = ["pratt"] }
ariadne = "0.5.1"
pretty = "0.12.5"

[dev-dependencies]
indoc = "2.0"
insta = "1.39"
