/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DASH_GT = 5,
  anon_sym_COLON = 6,
  anon_sym_LT = 7,
  anon_sym_GT = 8,
  anon_sym_let = 9,
  anon_sym_mut = 10,
  anon_sym_EQ = 11,
  anon_sym_SEMI = 12,
  anon_sym_if = 13,
  anon_sym_else = 14,
  anon_sym_while = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_return = 18,
  anon_sym_BANG = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_PERCENT = 23,
  anon_sym_PLUS = 24,
  anon_sym_LT_EQ = 25,
  anon_sym_GT_EQ = 26,
  anon_sym_EQ_EQ = 27,
  anon_sym_BANG_EQ = 28,
  anon_sym_AMP_AMP = 29,
  anon_sym_PIPE_PIPE = 30,
  sym_integer_literal = 31,
  sym_boolean_literal = 32,
  sym_identifier = 33,
  sym_source_file = 34,
  sym_definition = 35,
  sym_function_definition = 36,
  sym_parameter = 37,
  sym_type_annotation = 38,
  sym__statement = 39,
  sym_variable_declaration = 40,
  sym_assignment = 41,
  sym_if_statement = 42,
  sym_while_statement = 43,
  sym_block = 44,
  sym_return_statement = 45,
  sym__expression_statement = 46,
  sym_expression = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_function_definition_repeat1 = 49,
  aux_sym_type_annotation_repeat1 = 50,
  aux_sym_if_statement_repeat1 = 51,
  aux_sym_block_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [sym_integer_literal] = "integer_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter] = "parameter",
  [sym_type_annotation] = "type_annotation",
  [sym__statement] = "_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_assignment] = "assignment",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_block] = "block",
  [sym_return_statement] = "return_statement",
  [sym__expression_statement] = "_expression_statement",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_type_annotation_repeat1] = "type_annotation_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [sym_integer_literal] = sym_integer_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter] = sym_parameter,
  [sym_type_annotation] = sym_type_annotation,
  [sym__statement] = sym__statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_assignment] = sym_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_block] = sym_block,
  [sym_return_statement] = sym_return_statement,
  [sym__expression_statement] = sym__expression_statement,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_type_annotation_repeat1] = aux_sym_type_annotation_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_annotation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 2,
  [7] = 3,
  [8] = 2,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 21,
  [23] = 21,
  [24] = 19,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 38,
  [42] = 37,
  [43] = 43,
  [44] = 40,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 38,
  [95] = 37,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 40,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '!', 59,
        '%', 64,
        '&', 5,
        '(', 35,
        ')', 37,
        '*', 62,
        '+', 65,
        ',', 36,
        '-', 61,
        '/', 63,
        ':', 39,
        ';', 47,
        '<', 40,
        '=', 46,
        '>', 41,
        'e', 18,
        'f', 9,
        'i', 15,
        'l', 10,
        'm', 30,
        'r', 14,
        't', 23,
        'w', 16,
        '{', 54,
        '|', 32,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(58);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == '-') ADVANCE(60);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(75);
      if (lookahead == 't') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 58,
        '(', 35,
        '-', 60,
        'e', 86,
        'f', 75,
        'i', 81,
        'l', 76,
        'r', 80,
        't', 88,
        'w', 82,
        '{', 54,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 58,
        '(', 35,
        '-', 60,
        'f', 75,
        'i', 81,
        'l', 76,
        'r', 80,
        't', 88,
        'w', 82,
        '{', 54,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 7,
        '%', 64,
        '&', 5,
        ')', 37,
        '*', 62,
        '+', 65,
        '-', 60,
        '/', 63,
        ';', 47,
        '<', 40,
        '=', 46,
        '>', 41,
        '|', 32,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(70);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == 'm') ADVANCE(97);
      if (lookahead == '{') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(69);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == '|') ADVANCE(71);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(66);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(67);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(68);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_boolean_literal);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_boolean_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 4},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 4},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_boolean_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(121),
    [sym_definition] = STATE(68),
    [sym_function_definition] = STATE(107),
    [aux_sym_source_file_repeat1] = STATE(68),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(4), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [49] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(2), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [98] = 13,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_let,
    ACTIONS(37), 1,
      anon_sym_if,
    ACTIONS(40), 1,
      anon_sym_while,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_return,
    ACTIONS(54), 1,
      sym_integer_literal,
    ACTIONS(57), 1,
      sym_boolean_literal,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(29), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(4), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [147] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(6), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [196] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(4), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [245] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(8), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [294] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(25), 1,
      sym_boolean_literal,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(4), 9,
      sym__statement,
      sym_variable_declaration,
      sym_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_block,
      sym_return_statement,
      sym__expression_statement,
      aux_sym_block_repeat1,
  [343] = 6,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [372] = 3,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [395] = 2,
    ACTIONS(89), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [416] = 2,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [437] = 2,
    ACTIONS(89), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [458] = 4,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(89), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 9,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [483] = 5,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [510] = 3,
    ACTIONS(89), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [533] = 7,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
  [564] = 2,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [585] = 9,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [619] = 9,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [653] = 9,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [687] = 9,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [721] = 9,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [755] = 9,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [789] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(107), 1,
      anon_sym_SEMI,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [820] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [851] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [882] = 4,
    ACTIONS(117), 1,
      anon_sym_else,
    STATE(35), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(113), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(115), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [905] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [936] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [967] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(121), 1,
      anon_sym_SEMI,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [998] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1029] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1060] = 4,
    ACTIONS(131), 1,
      anon_sym_else,
    STATE(34), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(127), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(129), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1083] = 4,
    ACTIONS(138), 1,
      anon_sym_else,
    STATE(34), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(134), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(136), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1106] = 8,
    ACTIONS(91), 1,
      anon_sym_AMP_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1137] = 2,
    ACTIONS(142), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(144), 7,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1155] = 2,
    ACTIONS(146), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(148), 7,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1173] = 2,
    ACTIONS(150), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(152), 7,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1191] = 2,
    ACTIONS(154), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(156), 7,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1209] = 2,
    ACTIONS(146), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(148), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1226] = 2,
    ACTIONS(142), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(144), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1243] = 2,
    ACTIONS(158), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(160), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1260] = 2,
    ACTIONS(154), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(156), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1277] = 2,
    ACTIONS(162), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(164), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1294] = 2,
    ACTIONS(166), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(168), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1311] = 2,
    ACTIONS(170), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(172), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1328] = 2,
    ACTIONS(174), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(176), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1345] = 2,
    ACTIONS(178), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(180), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1362] = 2,
    ACTIONS(182), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(184), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1379] = 2,
    ACTIONS(186), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(188), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1396] = 2,
    ACTIONS(190), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer_literal,
    ACTIONS(192), 6,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_boolean_literal,
      sym_identifier,
  [1413] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1434] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(32), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1452] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(17), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1470] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(18), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1488] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(31), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1506] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(9), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1524] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(33), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1542] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(16), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1560] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(25), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1578] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(26), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1596] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(27), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1614] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(30), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1632] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(14), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1650] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(11), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1668] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(15), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      sym_boolean_literal,
      sym_identifier,
  [1686] = 4,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    STATE(107), 1,
      sym_function_definition,
    STATE(70), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [1700] = 2,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(198), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_LBRACE,
  [1710] = 4,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 1,
      anon_sym_fn,
    STATE(107), 1,
      sym_function_definition,
    STATE(70), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [1724] = 1,
    ACTIONS(207), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_LBRACE,
  [1731] = 1,
    ACTIONS(209), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_LBRACE,
  [1738] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_function_definition_repeat1,
  [1748] = 3,
    ACTIONS(215), 1,
      anon_sym_DASH_GT,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(93), 1,
      sym_block,
  [1758] = 3,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_type_annotation_repeat1,
  [1768] = 3,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_GT,
    STATE(75), 1,
      aux_sym_type_annotation_repeat1,
  [1778] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_type_annotation_repeat1,
  [1788] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_if,
    STATE(51), 1,
      sym_block,
  [1798] = 3,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_function_definition_repeat1,
  [1808] = 3,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    ACTIONS(237), 1,
      anon_sym_DASH_GT,
    STATE(104), 1,
      sym_block,
  [1818] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_function_definition_repeat1,
  [1828] = 3,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    ACTIONS(241), 1,
      anon_sym_DASH_GT,
    STATE(97), 1,
      sym_block,
  [1838] = 3,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(245), 1,
      sym_identifier,
    STATE(81), 1,
      sym_parameter,
  [1848] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_if,
    STATE(49), 1,
      sym_block,
  [1858] = 1,
    ACTIONS(247), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1863] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(101), 1,
      sym_type_annotation,
  [1870] = 1,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1875] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(97), 1,
      sym_block,
  [1882] = 2,
    ACTIONS(251), 1,
      anon_sym_mut,
    ACTIONS(253), 1,
      sym_identifier,
  [1889] = 1,
    ACTIONS(255), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1894] = 1,
    ACTIONS(235), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1899] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(110), 1,
      sym_type_annotation,
  [1906] = 1,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1911] = 1,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1916] = 1,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1921] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(76), 1,
      sym_type_annotation,
  [1928] = 1,
    ACTIONS(259), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1933] = 2,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
  [1940] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(90), 1,
      sym_type_annotation,
  [1947] = 1,
    ACTIONS(263), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1952] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_block,
  [1959] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(87), 1,
      sym_type_annotation,
  [1966] = 2,
    ACTIONS(245), 1,
      sym_identifier,
    STATE(91), 1,
      sym_parameter,
  [1973] = 1,
    ACTIONS(265), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1978] = 2,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(88), 1,
      sym_type_annotation,
  [1985] = 1,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1990] = 1,
    ACTIONS(267), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1995] = 2,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [2002] = 2,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block,
  [2009] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(100), 1,
      sym_block,
  [2016] = 1,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
  [2020] = 1,
    ACTIONS(271), 1,
      sym_identifier,
  [2024] = 1,
    ACTIONS(273), 1,
      anon_sym_COLON,
  [2028] = 1,
    ACTIONS(275), 1,
      anon_sym_EQ,
  [2032] = 1,
    ACTIONS(230), 1,
      anon_sym_if,
  [2036] = 1,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
  [2040] = 1,
    ACTIONS(279), 1,
      anon_sym_LPAREN,
  [2044] = 1,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
  [2048] = 1,
    ACTIONS(283), 1,
      sym_identifier,
  [2052] = 1,
    ACTIONS(285), 1,
      anon_sym_EQ,
  [2056] = 1,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 147,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 245,
  [SMALL_STATE(8)] = 294,
  [SMALL_STATE(9)] = 343,
  [SMALL_STATE(10)] = 372,
  [SMALL_STATE(11)] = 395,
  [SMALL_STATE(12)] = 416,
  [SMALL_STATE(13)] = 437,
  [SMALL_STATE(14)] = 458,
  [SMALL_STATE(15)] = 483,
  [SMALL_STATE(16)] = 510,
  [SMALL_STATE(17)] = 533,
  [SMALL_STATE(18)] = 564,
  [SMALL_STATE(19)] = 585,
  [SMALL_STATE(20)] = 619,
  [SMALL_STATE(21)] = 653,
  [SMALL_STATE(22)] = 687,
  [SMALL_STATE(23)] = 721,
  [SMALL_STATE(24)] = 755,
  [SMALL_STATE(25)] = 789,
  [SMALL_STATE(26)] = 820,
  [SMALL_STATE(27)] = 851,
  [SMALL_STATE(28)] = 882,
  [SMALL_STATE(29)] = 905,
  [SMALL_STATE(30)] = 936,
  [SMALL_STATE(31)] = 967,
  [SMALL_STATE(32)] = 998,
  [SMALL_STATE(33)] = 1029,
  [SMALL_STATE(34)] = 1060,
  [SMALL_STATE(35)] = 1083,
  [SMALL_STATE(36)] = 1106,
  [SMALL_STATE(37)] = 1137,
  [SMALL_STATE(38)] = 1155,
  [SMALL_STATE(39)] = 1173,
  [SMALL_STATE(40)] = 1191,
  [SMALL_STATE(41)] = 1209,
  [SMALL_STATE(42)] = 1226,
  [SMALL_STATE(43)] = 1243,
  [SMALL_STATE(44)] = 1260,
  [SMALL_STATE(45)] = 1277,
  [SMALL_STATE(46)] = 1294,
  [SMALL_STATE(47)] = 1311,
  [SMALL_STATE(48)] = 1328,
  [SMALL_STATE(49)] = 1345,
  [SMALL_STATE(50)] = 1362,
  [SMALL_STATE(51)] = 1379,
  [SMALL_STATE(52)] = 1396,
  [SMALL_STATE(53)] = 1413,
  [SMALL_STATE(54)] = 1434,
  [SMALL_STATE(55)] = 1452,
  [SMALL_STATE(56)] = 1470,
  [SMALL_STATE(57)] = 1488,
  [SMALL_STATE(58)] = 1506,
  [SMALL_STATE(59)] = 1524,
  [SMALL_STATE(60)] = 1542,
  [SMALL_STATE(61)] = 1560,
  [SMALL_STATE(62)] = 1578,
  [SMALL_STATE(63)] = 1596,
  [SMALL_STATE(64)] = 1614,
  [SMALL_STATE(65)] = 1632,
  [SMALL_STATE(66)] = 1650,
  [SMALL_STATE(67)] = 1668,
  [SMALL_STATE(68)] = 1686,
  [SMALL_STATE(69)] = 1700,
  [SMALL_STATE(70)] = 1710,
  [SMALL_STATE(71)] = 1724,
  [SMALL_STATE(72)] = 1731,
  [SMALL_STATE(73)] = 1738,
  [SMALL_STATE(74)] = 1748,
  [SMALL_STATE(75)] = 1758,
  [SMALL_STATE(76)] = 1768,
  [SMALL_STATE(77)] = 1778,
  [SMALL_STATE(78)] = 1788,
  [SMALL_STATE(79)] = 1798,
  [SMALL_STATE(80)] = 1808,
  [SMALL_STATE(81)] = 1818,
  [SMALL_STATE(82)] = 1828,
  [SMALL_STATE(83)] = 1838,
  [SMALL_STATE(84)] = 1848,
  [SMALL_STATE(85)] = 1858,
  [SMALL_STATE(86)] = 1863,
  [SMALL_STATE(87)] = 1870,
  [SMALL_STATE(88)] = 1875,
  [SMALL_STATE(89)] = 1882,
  [SMALL_STATE(90)] = 1889,
  [SMALL_STATE(91)] = 1894,
  [SMALL_STATE(92)] = 1899,
  [SMALL_STATE(93)] = 1906,
  [SMALL_STATE(94)] = 1911,
  [SMALL_STATE(95)] = 1916,
  [SMALL_STATE(96)] = 1921,
  [SMALL_STATE(97)] = 1928,
  [SMALL_STATE(98)] = 1933,
  [SMALL_STATE(99)] = 1940,
  [SMALL_STATE(100)] = 1947,
  [SMALL_STATE(101)] = 1952,
  [SMALL_STATE(102)] = 1959,
  [SMALL_STATE(103)] = 1966,
  [SMALL_STATE(104)] = 1973,
  [SMALL_STATE(105)] = 1978,
  [SMALL_STATE(106)] = 1985,
  [SMALL_STATE(107)] = 1990,
  [SMALL_STATE(108)] = 1995,
  [SMALL_STATE(109)] = 2002,
  [SMALL_STATE(110)] = 2009,
  [SMALL_STATE(111)] = 2016,
  [SMALL_STATE(112)] = 2020,
  [SMALL_STATE(113)] = 2024,
  [SMALL_STATE(114)] = 2028,
  [SMALL_STATE(115)] = 2032,
  [SMALL_STATE(116)] = 2036,
  [SMALL_STATE(117)] = 2040,
  [SMALL_STATE(118)] = 2044,
  [SMALL_STATE(119)] = 2048,
  [SMALL_STATE(120)] = 2052,
  [SMALL_STATE(121)] = 2056,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 6, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 6, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_statement, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_statement, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 5, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 5, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_annotation_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_annotation_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [287] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_starstream(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "starstream",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
