[package]
name = "starstream-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "starstream"
path = "src/main.rs"

[dependencies]
starstream-compiler = { path = "../starstream-compiler" }
starstream-to-wasm = { path = "../starstream-to-wasm" }
console = "0.16.0"
clap = { version = "4.5.32", features = ["derive"] }
ariadne = "0.5.1"
miette = { version = "7.6.0", features = ["fancy"] }
ignore = "0.4.24"
walkdir = "2.5.0"
similar = "2.7.0"
