package starstream:node-rpc;

interface registry {
    record component-interface {
        wit: string,
        entrypoint: string
    }

    get-wit: func(hash: string, resolve: bool) -> component-interface;
}
interface handler {
    /// TODO: other RPC methods for the ledger
}

use starstream:wrpc-multiplexer/handler as multiplexer;

world client {
    import multiplexer;
    import handler;
    import registry;
}

world server {
    export multiplexer;
    export handler;
    export registry;
}

