package starstream:node-rpc;

interface handler {
    /// TODO: other RPC methods for the ledger
}

use starstream:wrpc-multiplexer/handler as multiplexer;
use starstream:registry/handler as registry;

world client {
    import multiplexer;
    import handler;
    import registry;
}

world server {
    export multiplexer;
    export handler;
    export registry;
}

