// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_snapshot_state_cabi<T: Guest>() -> i64 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let result0 = T::snapshot_state();
    _rt::as_i64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_snapshot_restore_cabi<T: Guest>(arg0: i64) {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    T::snapshot_restore(arg0 as u64);
}
pub trait Guest {
    fn snapshot_state() -> u64;
    fn snapshot_restore(state: u64) -> ();
}
#[doc(hidden)]
macro_rules! __export_world_demo_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "snapshot-state")] unsafe extern "C" fn
        export_snapshot_state() -> i64 { unsafe { $($path_to_types)*::
        _export_snapshot_state_cabi::<$ty > () } } #[unsafe (export_name =
        "snapshot-restore")] unsafe extern "C" fn export_snapshot_restore(arg0 : i64,) {
        unsafe { $($path_to_types)*:: _export_snapshot_restore_cabi::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_demo_cabi;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod starstream_demo {
    pub mod utxo_a_rs {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod ledger {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn burn() -> () {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "starstream-demo:utxo-a-rs/ledger")]
                    unsafe extern "C" {
                        #[link_name = "burn"]
                        fn wit_import0();
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() {
                        unreachable!()
                    }
                    unsafe { wit_import0() };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod starstream_demo {
        pub mod utxo_a_rs {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod utxo_a_api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Utxo {
                    handle: _rt::Resource<Utxo>,
                }
                type _UtxoRep<T> = Option<T>;
                impl Utxo {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Utxo`.
                    pub fn new<T: GuestUtxo>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _UtxoRep<T> = Some(val);
                        let ptr: *mut _UtxoRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestUtxo>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestUtxo>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestUtxo>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _UtxoRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestUtxo>(&self) -> *mut _UtxoRep<T> {
                        Utxo::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Utxo`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct UtxoBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Utxo>,
                }
                impl<'a> UtxoBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestUtxo>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _UtxoRep<T> {
                        Utxo::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Utxo {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]starstream-demo:utxo-a-rs/utxo-a-api"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]utxo"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_utxo_cabi<T: GuestUtxo>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = Utxo::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_utxo_get_data_cabi<T: GuestUtxo>(
                    arg0: *mut u8,
                ) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_data(
                        unsafe { UtxoBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    _rt::as_i64(result0)
                }
                pub trait Guest {
                    type Utxo: GuestUtxo;
                }
                pub trait GuestUtxo: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]starstream-demo:utxo-a-rs/utxo-a-api"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]utxo"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]starstream-demo:utxo-a-rs/utxo-a-api"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]utxo"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                    fn get_data(&self) -> u64;
                }
                #[doc(hidden)]
                macro_rules! __export_starstream_demo_utxo_a_rs_utxo_a_api_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "starstream-demo:utxo-a-rs/utxo-a-api#[constructor]utxo")] unsafe
                        extern "C" fn export_constructor_utxo() -> i32 { unsafe {
                        $($path_to_types)*:: _export_constructor_utxo_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Utxo > () } } #[unsafe (export_name
                        = "starstream-demo:utxo-a-rs/utxo-a-api#[method]utxo.get-data")]
                        unsafe extern "C" fn export_method_utxo_get_data(arg0 : * mut
                        u8,) -> i64 { unsafe { $($path_to_types)*::
                        _export_method_utxo_get_data_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Utxo > (arg0) } } const _ : () = { #[doc(hidden)]
                        #[unsafe (export_name =
                        "starstream-demo:utxo-a-rs/utxo-a-api#[dtor]utxo")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Utxo::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Utxo > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_starstream_demo_utxo_a_rs_utxo_a_api_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_demo_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_demo_cabi!($ty with_types_in
        $($path_to_types_root)*); $($path_to_types_root)*::
        exports::starstream_demo::utxo_a_rs::utxo_a_api::__export_starstream_demo_utxo_a_rs_utxo_a_api_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::starstream_demo::utxo_a_rs::utxo_a_api);
    };
}
#[doc(inline)]
pub(crate) use __export_demo_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:starstream-demo:utxo-a-rs:demo:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 398] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x93\x02\x01A\x02\x01\
A\x08\x01B\x02\x01@\0\x01\0\x04\0\x04burn\x01\0\x03\0\x20starstream-demo:utxo-a-\
rs/ledger\x05\0\x01@\0\0w\x04\0\x0esnapshot-state\x01\x01\x01@\x01\x05statew\x01\
\0\x04\0\x10snapshot-restore\x01\x02\x01B\x07\x04\0\x04utxo\x03\x01\x01i\0\x01@\0\
\0\x01\x04\0\x11[constructor]utxo\x01\x02\x01h\0\x01@\x01\x04self\x03\0w\x04\0\x15\
[method]utxo.get-data\x01\x04\x04\0$starstream-demo:utxo-a-rs/utxo-a-api\x05\x03\
\x04\0\x1estarstream-demo:utxo-a-rs/demo\x04\0\x0b\x0a\x01\0\x04demo\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rus\
t\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
