[package]
name = "starstream-to-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
starstream-types = { path = "../starstream-types" }
wasm-encoder = "0.240.0"
