[package]
name = "starstream-to-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
starstream-types = { workspace = true }
wasm-encoder = "0.240.0"

[dev-dependencies]
insta = { workspace = true }
wasmprinter = "0.240.0"
