[package]
name = "starstream_nova"
version = "0.0.0"
edition = "2024"
license = "MIT"

[dependencies]
# same as zkEngine, technically could be different,
# but we keep it the same
ff = "*"
typenum = "*"
combine = "4.6.7"

[dev-dependencies]
wat = "1.239.0"
